# Generated by Django 5.0.3 on 2024-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviedata_director_alter_moviedata_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='genre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='release_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
