# Generated by Django 5.0.3 on 2024-03-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_moviedata_genre_alter_moviedata_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/default.jpg', upload_to='Images/'),
        ),
    ]
